### ISSUE TITLE
Create Login

### ISSUE THREAD

**Issue by WendelHime** [CapivaraProjects/GreenEyes#6]
Create user logi using username and password(encrypted using SJCL). <br />
You can use this [tutorial](https://scotch.io/tutorials/react-native-app-with-authentication-and-user-management-in-15-minutes) or [this](http://stacktips.com/tutorials/react-native/creating-login-screen-in-react-native).<br /><br />

Remember to create tests and login should be able to make requests in GYResources!

**Comment by gvNN7** [comment]
Login Created, see Pull Request ID: #20
